// import type { Metadata } from "next";

import { Inter } from "next/font/google";
import "./globals.css";

import Headerr from "./components/main/Header";
import StoreProvider from "./StoreProvider";
import Footer from "./components/main/Footer";
import LoggedInHeader from "./components/main/LoggedInHeader";
import { useEffect, useState } from "react";
import { AuthProvider } from "./components/sub/AuthContext";
import { UserInfoProvider } from "./components/sub/UserInfoContext";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en" className="overflow-x-hidden" >
      <AuthProvider>
        <UserInfoProvider>
          <StoreProvider>
            <body className="">
              {/* {authenticated? <LoggedInHeader /> : <Header/>} */}
              {/* <LoggedInHeader /> */}
              <Headerr />
              {children}
              <Footer />
            </body>
          </StoreProvider>
        </UserInfoProvider>
      </AuthProvider>
    </html>
  );
}
